---
  - name: Restart chrony
    service:
      name: "{{ chrony_service }}"
      state: restarted
    when: chrony_allow_restart

  - name: Start chrony
    service:
      name: "{{ chrony_service }}"
      state: started
    when: chrony_manage_service
