---
  - name: Reload chrony
    service:
      name: "{{ chrony_service }}"
      state: reloaded

  - name: Restart chrony
    service:
      name: "{{ chrony_service }}"
      state: restarted

  - name: Start chrony
    service:
      name: "{{ chrony_service }}"
      state: started
